# Estágio de desenvolvimento
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine3.20 AS production

WORKDIR /app

COPY ./package*.json ./
COPY ./tsconfig* ./

RUN npm install --only=production

COPY --from=build /app/dist ./dist

ENTRYPOINT ["npm", "run", "start:prod"]
